<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aditya Das, Jashith, Manal Nazer">

<title>A2 Part 3 cuisines – Manal’s blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Manal’s blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A2 Part 3 cuisines</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Aditya Das, Jashith, Manal Nazer </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="a2-part-3-cuisines" class="level1">
<h1>A2 Part 3 cuisines</h1>
<p>A dataset of recipes scraped from Allrecipes.com, containing ingredients, cooking times, nutrition facts, country, ratings, and review counts. The data has been parsed and cleaned to ensure analysis- readiness.</p>
<section id="data-dictionary-to-be-revised" class="level2">
<h2 class="anchored" data-anchor-id="data-dictionary-to-be-revised">Data dictionary (to be revised)</h2>
<p>A data frame with 2218 rows and 17 variables:</p>
<p><strong>name</strong> Name of the recipe</p>
<p><strong>country</strong> The country/region the cuisine is from.</p>
<p><strong>url</strong> Link to the recipe</p>
<p><strong>author</strong> Author of the recipe</p>
<p><strong>date_published</strong> When the recipe was published/updated</p>
<p><strong>ingredients</strong> The ingredients of the recipe</p>
<p><strong>calories</strong> Calories per serving fat Fat per serving</p>
<p><strong>carbs</strong> carbs per serving</p>
<p><strong>protein</strong> Proteins per serving</p>
<p><strong>avg_rating</strong> Average rating out of 5 stars</p>
<p><strong>total_ratings</strong> Number of ratings received</p>
<p><strong>reviews</strong> Number of written reviews</p>
<p><strong>prep_time</strong> Preparation time in minutes</p>
<p><strong>cook_time</strong> Cooking time in minutes</p>
<p><strong>total_time</strong> Prep + cook time in minutes. Note that this value may not always match the actual total effort required, as other time-related fields (such as refrigeration, marination, fry time, or additional wait periods) have been excluded due to inconsistent availability across recipes</p>
<p><strong>servings</strong> Number of servings</p>
<hr>
</section>
<section id="our-questions-before-performing-eda" class="level2">
<h2 class="anchored" data-anchor-id="our-questions-before-performing-eda">Our questions before performing EDA:</h2>
<ul>
<li><p>How many unique countries are represented? Which countries contribute the most recipes?</p></li>
<li><p>What are the average, minimum, and maximum values of <strong>calories, fat, carbs, and protein</strong>?</p></li>
<li><p>Which recipes have the <strong>highest and lowest calories</strong>?</p></li>
<li><p>Are <strong>newer recipes</strong> (by <code>date_published</code>) rated differently from older ones?</p></li>
<li><p>What is the distribution of <strong>prep_time, cook_time, and total_time</strong>?</p></li>
<li><p>Which recipes are <strong>quickest</strong> vs <strong>most time-consuming</strong>?</p></li>
<li><p>Are longer recipes (higher total_time) rated higher or lower on average?</p></li>
<li><p>Which countries have the <strong>most calorie-dense dishes</strong>?</p></li>
<li><p>Do some cuisines tend to have <strong>healthier</strong> or <strong>lower-fat</strong> recipes?</p></li>
<li><p>Are there any noticeable <strong>regional trends</strong> in ratings or cooking times?</p></li>
</ul>
<hr>
<section id="setting-up-libraries" class="level4">
<h4 class="anchored" data-anchor-id="setting-up-libraries">Setting up libraries</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: scales</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggridges</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
New to ggformula?  Try the tutorials: 
    learnr::run_tutorial("introduction", package = "ggformula")
    learnr::run_tutorial("refining", package = "ggformula")</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'viridis'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:scales':

    viridis_pal</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tastyR)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ lubridate 1.9.4     ✔ stringr   1.5.2
✔ purrr     1.1.0     ✔ tibble    3.3.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor() masks scales::col_factor()
✖ purrr::discard()    masks scales::discard()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::lag()        masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic) <span class="co"># Our trusted friend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following object is masked from 'package:purrr':

    cross

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:scales':

    rescale

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula) <span class="co"># Formula interface to ggplot2</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd) <span class="co"># Michael Friendly's package, Visualizing Categorical</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid

Attaching package: 'vcd'

The following object is masked from 'package:mosaic':

    mplot</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra) <span class="co"># Categorical Data Sets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gnm

Attaching package: 'gnm'

The following object is masked from 'package:lattice':

    barley


Attaching package: 'vcdExtra'

The following object is masked from 'package:dplyr':

    summarise</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(resampledata) <span class="co"># More datasets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'resampledata'

The following object is masked from 'package:vcdExtra':

    TV

The following object is masked from 'package:datasets':

    Titanic</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(visStatistics) # Comprehensive all-in-one stats viz/test package</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmosaic) <span class="co"># Tidy Mosaic Plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggmosaic'

The following objects are masked from 'package:vcd':

    mosaic, spine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co"># Colours, Themes and new geometries in ggplot</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) <span class="co"># Data Cleaning and Tidying</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visdat) <span class="co"># Visualize whole dataframes for missing data</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar) <span class="co"># Clean missing data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'naniar'

The following object is masked from 'package:skimr':

    n_complete</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT) <span class="co"># Interactive Tables for our data</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tinytable) <span class="co"># Elegant Tables for our data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tinytable'

The following object is masked from 'package:ggplot2':

    theme_void</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel) <span class="co"># Repelling Text Labels in ggplot</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marquee) <span class="co"># Marquee Text in ggplot</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(crosstable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'crosstable'

The following object is masked from 'package:purrr':

    compact</code></pre>
</div>
</div>
</section>
<section id="reading-and-taking-a-look-at-the-data-set" class="level4">
<h4 class="anchored" data-anchor-id="reading-and-taking-a-look-at-the-data-set">Reading and taking a look at the data set:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cuisines, <span class="at">package =</span> <span class="st">"tastyR"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>cuisines1 <span class="ot">&lt;-</span> cuisines <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    janitor<span class="sc">::</span><span class="fu">clean_names</span>(<span class="at">case =</span> <span class="st">"snake"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(cuisines1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,218
Columns: 17
$ name           &lt;chr&gt; "Saganaki (Flaming Greek Cheese)", "Coney Island Knishe…
$ country        &lt;chr&gt; "Greek", "Jewish", "Australian and New Zealander", "Chi…
$ url            &lt;chr&gt; "https://www.allrecipes.com/recipe/263750/flaming-greek…
$ author         &lt;chr&gt; "John Mitzewich", "John Mitzewich", "CHIPPENDALE", "Hei…
$ date_published &lt;date&gt; 2024-02-07, 2024-11-26, 2022-07-14, 2025-01-31, 2025-0…
$ ingredients    &lt;chr&gt; "1 (4 ounce) package kasseri cheese, 1 tablespoon water…
$ calories       &lt;dbl&gt; 391, 301, 64, 106, 449, 958, 378, 90, 157, 322, 4, NA, …
$ fat            &lt;dbl&gt; 25, 17, 3, 9, 23, 24, 10, 5, 6, 16, 0, NA, 21, 2, 66, 8…
$ carbs          &lt;dbl&gt; 15, 31, 9, 7, 58, 144, 59, 10, 25, 39, 1, NA, 16, 63, 7…
$ protein        &lt;dbl&gt; 16, 7, 1, 1, 7, 46, 14, 1, 2, 7, 0, NA, 28, 6, 54, 17, …
$ avg_rating     &lt;dbl&gt; 4.8, 4.6, 4.3, 5.0, 3.8, 4.4, 4.3, NA, 4.6, 5.0, 4.7, 4…
$ total_ratings  &lt;dbl&gt; 25, 10, 126, 1, 13, 40, 3, NA, 65, 2, 182, 2, 19, 16, 9…
$ reviews        &lt;dbl&gt; 22, 9, 104, 1, 11, 32, 3, NA, 55, 2, 138, 2, 15, 16, 84…
$ prep_time      &lt;dbl&gt; 10, 30, 20, 10, 30, 30, 30, 40, 0, 5, 5, 5, 10, 10, 20,…
$ cook_time      &lt;dbl&gt; 5, 75, 15, 0, 15, 165, 75, 30, 0, 5, 0, 25, 10, 50, 16,…
$ total_time     &lt;dbl&gt; 15, 180, 180, 10, 45, 675, 585, 155, 0, 10, 5, 30, 50, …
$ servings       &lt;dbl&gt; 2, 16, 12, 6, 15, 6, 6, 84, 24, 1, 21, 8, 4, 10, 4, 8, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cuisines1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,218 × 17
   name     country url   author date_published ingredients calories   fat carbs
   &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;date&gt;         &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 Saganak… Greek   http… John … 2024-02-07     1 (4 ounce…      391    25    15
 2 Coney I… Jewish  http… John … 2024-11-26     2 ¾ cups a…      301    17    31
 3 Diana's… Austra… http… CHIPP… 2022-07-14     1 ½ cups w…       64     3     9
 4 Chilean… Chilean http… Heidi  2025-01-31     ½ cup chop…      106     9     7
 5 Tex-Mex… Tex-Mex http… Ann    2025-02-18     2 cups all…      449    23    58
 6 Newfoun… Canadi… http… MomWh… 2022-08-12     1 (3 pound…      958    24   144
 7 Pasta e… Italian http… Buckw… 2023-12-12     1 cup dry …      378    10    59
 8 Danish … Danish  http… TheOt… 2020-06-19     4 cups all…       90     5    10
 9 Lemon P… Amish … http… Laura… 2025-01-21     2 cups all…      157     6    25
10 Pan con… Spanish http… Luis … 2025-06-02     1 large to…      322    16    39
# ℹ 2,208 more rows
# ℹ 8 more variables: protein &lt;dbl&gt;, avg_rating &lt;dbl&gt;, total_ratings &lt;dbl&gt;,
#   reviews &lt;dbl&gt;, prep_time &lt;dbl&gt;, cook_time &lt;dbl&gt;, total_time &lt;dbl&gt;,
#   servings &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="inspecting-the-data" class="level4">
<h4 class="anchored" data-anchor-id="inspecting-the-data">Inspecting the data:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>visdat<span class="sc">::</span><span class="fu">vis_dat</span>(cuisines1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>visdat<span class="sc">::</span><span class="fu">vis_miss</span>(cuisines1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="observations" class="level3">
<h3 class="anchored" data-anchor-id="observations">Observations:</h3>
<ul>
<li>Several entries in the&nbsp;<strong>calories</strong>, <strong>fat</strong>, <strong>carbs</strong>, <strong>avg_rating</strong>, <strong>total_ratings</strong>, and <strong>reviews</strong> columns contained missing values. Although removing them could slightly reduce representation across cuisines, the missing data accounted for only about <strong>1.2%</strong> of the dataset, so we chose to drop these rows to maintain data quality and consistency.</li>
</ul>
</section>
<section id="dropping-the-nas" class="level3">
<h3 class="anchored" data-anchor-id="dropping-the-nas">Dropping the NA’s:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>cuisines2 <span class="ot">&lt;-</span> cuisines1 <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>tidyr<span class="sc">::</span><span class="fu">drop_na</span>() </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>cuisines2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,058 × 17
   name     country url   author date_published ingredients calories   fat carbs
   &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;date&gt;         &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 Saganak… Greek   http… John … 2024-02-07     1 (4 ounce…      391    25    15
 2 Coney I… Jewish  http… John … 2024-11-26     2 ¾ cups a…      301    17    31
 3 Diana's… Austra… http… CHIPP… 2022-07-14     1 ½ cups w…       64     3     9
 4 Chilean… Chilean http… Heidi  2025-01-31     ½ cup chop…      106     9     7
 5 Tex-Mex… Tex-Mex http… Ann    2025-02-18     2 cups all…      449    23    58
 6 Newfoun… Canadi… http… MomWh… 2022-08-12     1 (3 pound…      958    24   144
 7 Pasta e… Italian http… Buckw… 2023-12-12     1 cup dry …      378    10    59
 8 Lemon P… Amish … http… Laura… 2025-01-21     2 cups all…      157     6    25
 9 Pan con… Spanish http… Luis … 2025-06-02     1 large to…      322    16    39
10 Traci's… Filipi… http… Traci… 2022-08-28     2 tablespo…        4     0     1
# ℹ 2,048 more rows
# ℹ 8 more variables: protein &lt;dbl&gt;, avg_rating &lt;dbl&gt;, total_ratings &lt;dbl&gt;,
#   reviews &lt;dbl&gt;, prep_time &lt;dbl&gt;, cook_time &lt;dbl&gt;, total_time &lt;dbl&gt;,
#   servings &lt;dbl&gt;</code></pre>
</div>
</div>
<p>160 rows were removed out of the 2218 entries through this process.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>cuisines2 <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(country, <span class="at">sort=</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 49 × 2
   country                          n
   &lt;chr&gt;                        &lt;int&gt;
 1 Canadian                        66
 2 Chinese                         64
 3 Filipino                        64
 4 Indian                          64
 5 Cuban                           63
 6 Russian                         63
 7 Soul Food                       63
 8 French                          61
 9 Australian and New Zealander    60
10 Cajun and Creole                60
# ℹ 39 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>cuisines2 <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(country)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     name             country              url               author         
 Length:2058        Length:2058        Length:2058        Length:2058       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
 date_published       ingredients           calories           fat        
 Min.   :2009-02-09   Length:2058        Min.   :   3.0   Min.   :  0.00  
 1st Qu.:2022-11-07   Class :character   1st Qu.: 193.0   1st Qu.:  7.00  
 Median :2024-07-13   Mode  :character   Median : 321.5   Median : 15.00  
 Mean   :2023-11-07                      Mean   : 359.4   Mean   : 18.56  
 3rd Qu.:2024-12-19                      3rd Qu.: 479.8   3rd Qu.: 25.00  
 Max.   :2025-07-29                      Max.   :2266.0   Max.   :190.00  
     carbs           protein         avg_rating    total_ratings   
 Min.   :  1.00   Min.   :  0.00   Min.   :1.000   Min.   :  1.00  
 1st Qu.: 13.00   1st Qu.:  4.00   1st Qu.:4.300   1st Qu.:  6.00  
 Median : 26.00   Median : 12.00   Median :4.600   Median : 25.00  
 Mean   : 32.01   Mean   : 16.72   Mean   :4.507   Mean   : 86.54  
 3rd Qu.: 45.00   3rd Qu.: 26.00   3rd Qu.:4.800   3rd Qu.: 90.00  
 Max.   :264.00   Max.   :135.00   Max.   :5.000   Max.   :997.00  
    reviews         prep_time        cook_time        total_time     
 Min.   :  1.00   Min.   :   0.0   Min.   :  0.00   Min.   :    0.0  
 1st Qu.:  6.00   1st Qu.:  10.0   1st Qu.: 10.00   1st Qu.:   35.0  
 Median : 22.00   Median :  15.0   Median : 25.00   Median :   60.0  
 Mean   : 77.84   Mean   :  21.9   Mean   : 42.84   Mean   :  175.5  
 3rd Qu.: 75.00   3rd Qu.:  25.0   3rd Qu.: 45.00   3rd Qu.:  120.0  
 Max.   :975.00   Max.   :1800.0   Max.   :600.00   Max.   :14440.0  
    servings     
 Min.   :  1.00  
 1st Qu.:  4.00  
 Median :  8.00  
 Mean   : 10.41  
 3rd Qu.: 12.00  
 Max.   :240.00  </code></pre>
</div>
</div>
</section>
<section id="observations-1" class="level3">
<h3 class="anchored" data-anchor-id="observations-1">Observations:</h3>
<ul>
<li><p>Of the 49 cuisine types in the dataset, 40 represent countries while 9 represent non-country categories (religious/cultural groups, regional cuisines, and cuisine styles).</p></li>
<li><p>The original “country” label was misleading since the data includes not just countries, but also religious groups (Jewish), cultural groups (Amish and Mennonite), regional cuisines (Tex-Mex, Southern Recipes), and cuisine styles (Soul Food). We renamed it to “cuisines_type” because users searching for recipes think in terms of cuisine styles rather than geographic or cultural distinctions.</p></li>
<li><p>The top cuisine types by recipe count are Canadian (66), Chinese (64), Filipino (64), Indian (64), Cuban (63), Russian (63), Soul Food (63), French (61), Australian and New Zealander (60), Cajun and Creole (60), Jewish (60), and Polish (60).</p></li>
</ul>
<section id="renaming-country-to-cuisine_type" class="level4">
<h4 class="anchored" data-anchor-id="renaming-country-to-cuisine_type">renaming country to cuisine_type:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="ot">&lt;-</span> cuisines2 <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="st">"cuisines_type"</span> <span class="ot">=</span> country)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>cuisines3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,058 × 17
   name     cuisines_type url   author date_published ingredients calories   fat
   &lt;chr&gt;    &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;  &lt;date&gt;         &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt;
 1 Saganak… Greek         http… John … 2024-02-07     1 (4 ounce…      391    25
 2 Coney I… Jewish        http… John … 2024-11-26     2 ¾ cups a…      301    17
 3 Diana's… Australian a… http… CHIPP… 2022-07-14     1 ½ cups w…       64     3
 4 Chilean… Chilean       http… Heidi  2025-01-31     ½ cup chop…      106     9
 5 Tex-Mex… Tex-Mex       http… Ann    2025-02-18     2 cups all…      449    23
 6 Newfoun… Canadian      http… MomWh… 2022-08-12     1 (3 pound…      958    24
 7 Pasta e… Italian       http… Buckw… 2023-12-12     1 cup dry …      378    10
 8 Lemon P… Amish and Me… http… Laura… 2025-01-21     2 cups all…      157     6
 9 Pan con… Spanish       http… Luis … 2025-06-02     1 large to…      322    16
10 Traci's… Filipino      http… Traci… 2022-08-28     2 tablespo…        4     0
# ℹ 2,048 more rows
# ℹ 9 more variables: carbs &lt;dbl&gt;, protein &lt;dbl&gt;, avg_rating &lt;dbl&gt;,
#   total_ratings &lt;dbl&gt;, reviews &lt;dbl&gt;, prep_time &lt;dbl&gt;, cook_time &lt;dbl&gt;,
#   total_time &lt;dbl&gt;, servings &lt;dbl&gt;</code></pre>
</div>
</div>
<hr>
</section>
<section id="checking-for-dates-published" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-dates-published">Checking for dates published:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(date_published)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 710 × 2
   date_published     n
   &lt;date&gt;         &lt;int&gt;
 1 2009-02-09         1
 2 2011-02-11         1
 3 2011-10-19         1
 4 2013-06-20         1
 5 2014-06-10         1
 6 2017-04-05         2
 7 2017-11-09         1
 8 2017-12-21         1
 9 2018-03-21         6
10 2018-06-08         5
# ℹ 700 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="sc">~</span>date_published) <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title=</span><span class="st">"Distribution of Date Published in the recipes dataset"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_date_published =</span> <span class="fu">median</span>(date_published, <span class="at">na.rm =</span> T),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_date_published =</span> <span class="fu">min</span>(date_published, <span class="at">na.rm=</span>T),</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_date_published =</span> <span class="fu">max</span>(date_published, <span class="at">na.rm=</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  median_date_published min_date_published max_date_published
  &lt;date&gt;                &lt;date&gt;             &lt;date&gt;            
1 2024-07-13            2009-02-09         2025-07-29        </code></pre>
</div>
</div>
</section>
</section>
<section id="observations-2" class="level3">
<h3 class="anchored" data-anchor-id="observations-2">Observations:</h3>
<p>The publication dates range from 2009-02-09 to 2025-07-29, confirming this is a recently scraped dataset. The median date of 2024-07-13 and the histogram distribution indicate that most recipes were either published or collected in mid-2024, likely reflecting when the data was scraped from Allrecipes.com.</p>
<hr>
<p>What are the average, minimum, and maximum values of <strong>calories, fat, carbs, and protein</strong>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean_calories =</span> <span class="fu">mean</span>(calories, <span class="at">na.rm=</span>T),</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">min_calories =</span> <span class="fu">min</span>(calories, <span class="at">na.rm =</span> T),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max_calories =</span> <span class="fu">max</span>(calories, <span class="at">na.rm =</span> T)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_calories min_calories max_calories
          &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
1          359.            3         2266</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean_fat =</span> <span class="fu">mean</span>(fat, <span class="at">na.rm=</span>T),</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">min_fat =</span> <span class="fu">min</span>(fat, <span class="at">na.rm =</span> T),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max_fat =</span> <span class="fu">max</span>(fat, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_fat min_fat max_fat
     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     18.6       0     190</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean_carbs =</span> <span class="fu">mean</span>(carbs, <span class="at">na.rm=</span>T),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">min_carbs =</span> <span class="fu">min</span>(carbs, <span class="at">na.rm =</span> T),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max_carbs =</span> <span class="fu">max</span>(carbs, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_carbs min_carbs max_carbs
       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1       32.0         1       264</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">mean_protein =</span> <span class="fu">mean</span>(protein, <span class="at">na.rm=</span>T),</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">min_protein =</span> <span class="fu">min</span>(protein, <span class="at">na.rm =</span> T),</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max_protein =</span> <span class="fu">max</span>(protein, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_protein min_protein max_protein
         &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1         16.7           0         135</code></pre>
</div>
</div>
</section>
<section id="observations-3" class="level3">
<h3 class="anchored" data-anchor-id="observations-3">Observations:</h3>
<p>This data set seems to be a diverse recipe collection spanning light to indulgent, with the average recipe being a reasonably balanced, moderate-calorie meal.</p>
<p>The calories span from 3 (likely a condiment, garnish, or data error) to 2,266 calories rich dessert, deep-fried dish, or family-style/party recipe).</p>
<p>0g minimum protein suggests vegetable-based or carb-heavy dishes (pasta, bread) and 135g maximum suggests very protein-focused dishes (likely meat-heavy).</p>
<p>1g minimum carbs likely implies meat/egg-focused dishes and 264g maximum carbs suggests pasta dishes, rice bowls, or baked goods.</p>
<p>0g fat shows fat-free recipes (rare in cooking) and 190g fat shows very rich/fried dishes, cheese-heavy, or desserts with butter/cream.</p>
<p>Overall, the mean values suggest most recipes aim for balanced nutrition, not extreme in any direction.We should be mindful of the outliers: maximum values (2,266 cal, 264g carbs, 190g fat) could skew analysis - these are likely special occasion foods or recipes meant to serve many people. The extremes might actually be total recipe values rather than per-serving, which would explain the wild maximums</p>
<hr>
<section id="we-checked-for-what-recipes-had-3-calories" class="level4">
<h4 class="anchored" data-anchor-id="we-checked-for-what-recipes-had-3-calories">We checked for what recipes had 3 calories:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(calories <span class="sc">==</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 17
  name      cuisines_type url   author date_published ingredients calories   fat
  &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;  &lt;date&gt;         &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt;
1 Simple C… Cajun and Cr… http… azstud 2025-03-05     2 ½ tables…        3     0
# ℹ 9 more variables: carbs &lt;dbl&gt;, protein &lt;dbl&gt;, avg_rating &lt;dbl&gt;,
#   total_ratings &lt;dbl&gt;, reviews &lt;dbl&gt;, prep_time &lt;dbl&gt;, cook_time &lt;dbl&gt;,
#   total_time &lt;dbl&gt;, servings &lt;dbl&gt;</code></pre>
</div>
</div>
<p>From this, we are sure that the dataset contains not only normal portioned dishes but also seasonings and condiments. Could drinks also come under small caloried items?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"drink|beverage|smoothie|juice|coffee|tea|cocktail|shake|lemonade|agua|lassi"</span>, </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>               name, <span class="at">ignore.case =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, cuisines_type, calories) <span class="sc">%&gt;%</span> </span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(calories)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 66 × 3
   name                          cuisines_type    calories
   &lt;chr&gt;                         &lt;chr&gt;               &lt;dbl&gt;
 1 Chinese Steamed Buns          Chinese                44
 2 Brazilian Coffee Cookies      Brazilian              49
 3 Indian Lassi                  Indian                 50
 4 Thai Coffee                   Thai                   64
 5 Chinese Tea Eggs              Chinese                75
 6 Swedish Tea Ring              Scandinavian           83
 7 Russian Tea Cakes             Russian               101
 8 Vietnamese Iced Coffee        Vietnamese            129
 9 Sweet Tea Peaches             Southern Recipes      131
10 Refreshing Brazilian Lemonade Brazilian             145
# ℹ 56 more rows</code></pre>
</div>
</div>
<hr>
</section>
<section id="we-explored-recipe-ratings-over-time" class="level4">
<h4 class="anchored" data-anchor-id="we-explored-recipe-ratings-over-time">We explored recipe ratings over time:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(avg_rating <span class="sc">~</span> date_published, <span class="at">color =</span> <span class="st">"maroon"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title=</span> <span class="st">"Recipe Ratings Over Time"</span>,</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">x=</span> <span class="st">"date published"</span>,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">y=</span><span class="st">"average ratings"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="observations-4" class="level3">
<h3 class="anchored" data-anchor-id="observations-4">Observations:</h3>
<p>The trend line shows ratings starting around 3.5 in 2009 and climbing to around 4.5+ by 2025. There’s a clear upward trend over time. Most recipes are highly rated, the vast majority of points cluster between 4.0-5.0 stars. There are very few points below 3.0 stars across any time period. Low ratings are rare outliers. The upward trend could mean:</p>
<ul>
<li><p>Newer recipes are genuinely better (improved recipe testing?)</p></li>
<li><p>Only highly-rated recipes get published/kept in recent years</p></li>
<li><p>Survivorship bias (older poorly-rated recipes may have been removed)</p></li>
</ul>
<p>Newer recipes (post-2020) are rated significantly higher than older ones, with the average climbing from ~3.5 to ~4.5+ stars. However, this coincides with a massive increase in recipe volume, so it’s worth investigating whether this is a quality improvement or a data collection artifact.</p>
<section id="next-well-check-if-total_ratings-number-of-reviews-differs-by-year" class="level4">
<h4 class="anchored" data-anchor-id="next-well-check-if-total_ratings-number-of-reviews-differs-by-year">Next, we’ll check if total_ratings (number of reviews) differs by year</h4>
<p>newer recipes might have fewer ratings:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(total_ratings <span class="sc">~</span> date_published, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"maroon"</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue4"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Do Newer Recipes Have Fewer Ratings?"</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date Published"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Total Number of Ratings"</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="observations-5" class="level3">
<h3 class="anchored" data-anchor-id="observations-5">Observations:</h3>
<p>Older recipes have had more time but fewer ratings - This is counterintuitive! One would expect recipes from 2010 to have accumulated more ratings over 15 years, but they have very few. This might suggest that older recipes may be less visible/searchable on the platform or maybe even that the user base was much smaller in earlier years. Older recipes may also have been removed or not imported into current system.</p>
<p>The trend line is misleading here because it’s heavily weighted by the massive volume of recent data. The relationship isn’t really about “time to accumulate ratings”; it’s about when the platform became popular/active.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_ratings <span class="sc">&lt;=</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>total_ratings, <span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"seagreen4"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Recipes with 50 or Fewer Ratings"</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Total Ratings"</span>,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Recipes"</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>total_ratings, <span class="at">color =</span> <span class="st">"skyblue1"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">" Distribution of total Recipe Ratings"</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Total Ratings"</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Recipes"</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="observations-6" class="level3">
<h3 class="anchored" data-anchor-id="observations-6">Observations:</h3>
<p>The vast majority of recipes in this dataset have 10 or fewer ratings, which means their avg_rating might not be very reliable. A recipe with 1 rating of 5 stars looks the same as a recipe with 500 ratings averaging 5 stars, but they’re very different in terms of reliability. The earlier “Do Newer Recipes Have Fewer Ratings?” plot might be misleading because it’s dominated by these low-count recipes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_ratings <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(avg_rating <span class="sc">~</span> date_published, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"maroon"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Recipe Ratings Over Time (≥10 ratings only)"</span>,</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Filtered for more reliable ratings"</span>,</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date Published"</span>,</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Rating"</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="observations-7" class="level3">
<h3 class="anchored" data-anchor-id="observations-7">Observations:</h3>
<p>The linear trend line shows a clear upward movement, rising from approximately 4.15 in 2018 to about 4.55 by 2024–2025. Building on this observation, user rating behavior may also be becoming more generous over time.</p>
<p>Most ratings cluster between 4.0 and 5.0, with very few recipes rated below 4.0. One possible explanation is that users are more likely to rate recipes they enjoyed, leading to rating inflation. Another possibility is selection bias: people tend to rate only the recipes they chose to make, which were already appealing to them. The rating system may not effectively differentiate between mediocre and excellent recipes.</p>
<section id="filtering-for-top-represented-cuisines-in-the-data-set" class="level4">
<h4 class="anchored" data-anchor-id="filtering-for-top-represented-cuisines-in-the-data-set">Filtering for Top Represented Cuisines in the data set:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">gf_bar</span>(<span class="sc">~</span> <span class="fu">fct_infreq</span>(cuisines_type) , <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_labs</span>(</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Cuisine Type"</span>,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Recipes"</span>,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Top Cuisines by Recipe Count"</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>top_cuisines <span class="ot">&lt;-</span> cuisines3 <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(cuisines_type) <span class="sc">%&gt;%</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">60</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(cuisines_type)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cuisines_type <span class="sc">%in%</span> top_cuisines) <span class="sc">%&gt;%</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cuisines_type =</span> <span class="fu">fct_reorder</span>(cuisines_type, avg_rating, median)) <span class="sc">%&gt;%</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> avg_rating, <span class="at">y =</span> cuisines_type)) <span class="sc">+</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"gold"</span>) <span class="sc">+</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Cuisine Type"</span>,</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Average Rating"</span>,</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Rating Distribution by Cuisine Type"</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>French cuisine seems to be the most popular in this data set, followed by Cajun and Creole, both with very narrow boxes. Almost all the dishes are rated somewhere between 4 and 5 stars.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'GGally'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggmosaic':

    happy</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set theme with a safe font BEFORE making the plot</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">"sans"</span>))</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Then make your plot</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  GGally<span class="sc">::</span><span class="fu">ggpairs</span>(</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>    cuisines3 <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(),</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"calories"</span>, <span class="st">"fat"</span>, <span class="st">"carbs"</span>, <span class="st">"protein"</span>, <span class="st">"avg_rating"</span>, <span class="st">"total_ratings"</span>),</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">diag =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"barDiag"</span>, <span class="at">bins =</span> <span class="dv">30</span>)),</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"smooth"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">se=</span> <span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"red"</span>)),</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">4</span>)),</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">progress =</span> <span class="cn">FALSE</span>,</span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Nutritional Correlations"</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"sans"</span>))</span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Time variables</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  GGally<span class="sc">::</span><span class="fu">ggpairs</span>(</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    cuisines3 <span class="sc">%&gt;%</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(),</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"prep_time"</span>, <span class="st">"cook_time"</span>, <span class="st">"total_time"</span>, <span class="st">"servings"</span>),</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">progress =</span> <span class="cn">FALSE</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">diag =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"barDiag"</span>, <span class="at">bins =</span> <span class="dv">25</span>)),</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"smooth"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>)),</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">5</span>)),</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Recipe Time &amp; Servings Correlations"</span></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="observations-8" class="level3">
<h3 class="anchored" data-anchor-id="observations-8">Observations:</h3>
<p>In the Recipe Time &amp; Servings correlation chart, we find that there is a weak correlation overall between recipe time and servings. Recipes with long prep don’t necessarily have long cook times. Recipe timing and serving size are mostly independent variables. A recipe for 2 people could take 15 minutes or 3 hours.</p>
<ul>
<li><p>In the Nutritional Content Correlations chart, we find much more interesting patterns:</p></li>
<li><p>calories ↔︎ fat: 0.867*** (VERY strong - fat drives calories)</p></li>
<li><p>calories ↔︎ protein: 0.711*** (strong - protein also adds calories)</p></li>
<li><p>calories ↔︎ carbs: 0.595*** (moderate - carbs matter less than fat/protein)</p></li>
<li><p>fat ↔︎ protein: 0.573*** (moderate - dishes high in one tend to be high in the other)</p></li>
<li><p>avg_rating ↔︎ total_ratings: 0.087*** (weak - popular recipes aren’t necessarily better rated)</p></li>
<li><p>Nutrition has almost NO relationship with ratings (all correlations near zero)</p></li>
</ul>
<p>Through this, we found out that calorie content is mostly predicted by fat, then protein, then carbs and that people don’t rate recipes based on nutritional content.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>cuisines3 <span class="sc">%&gt;%</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(cuisines_type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Canadian"</span>, <span class="st">"Chinese"</span>,<span class="st">"Filipino"</span>, <span class="st">"Indian"</span>, <span class="st">"Cuban"</span>, <span class="st">"Russian"</span>)) <span class="sc">%&gt;%</span>  <span class="co"># Top 5 for clarity</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">gf_boxplot</span>(<span class="fu">reorder</span>(cuisines_type, total_time) <span class="sc">~</span> <span class="fu">log10</span>(total_time), </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> <span class="sc">~</span>cuisines_type, </span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">orientation =</span> <span class="st">"y"</span>, </span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_wrap</span>(<span class="fu">vars</span>(avg_rating)) <span class="sc">%&gt;%</span> </span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_fill_brewer</span>(<span class="at">type =</span> <span class="st">"qual"</span>, <span class="at">palette =</span> <span class="st">"Dark2"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Log Cooking Time by Cuisine Type (Faceted by Average Rating)"</span>,</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Log Total Time (minutes)"</span>,</span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Cuisine Type (ordered by time)"</span></span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cuisines_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Rating doesn’t necessarily correlate with cooking time: both quick and lengthy recipes can achieve high ratings. Cuisine-specific patterns persist across ratings; each cuisine maintains its characteristic cooking time profile regardless of rating. <strong>Cubans</strong> have the highest cooking time, followed by <strong>Russian</strong> cuisine. <strong>Chinese and Indian</strong> cuisines tend to cluster at lower cooking times (shorter preparation). <strong>Filipino</strong> appears relatively quick to prepare across rating levels.</p>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion:</h2>
<p>This exploratory data analysis of 2,218 recipes from Allrecipes.com revealed a diverse data set spanning 49 cuisine types, publication dates from 2009 to 2025, and a wide nutritional range. After cleaning, only 1.2% of entries were removed due to missing values.</p>
<p>Nutritional patterns show that calories are strongly driven by fat, followed by protein and carbs, while nutrition has almost no relationship with recipe ratings. Recipes range from minimal-calorie condiments to rich, multi-serving dishes, with averages suggesting generally balanced meals.</p>
<p>Over time, average recipe ratings have steadily increased from around 3.5 in 2009 to over 4.5 by 2025, likely reflecting rating inflation or platform evolution rather than drastic quality improvements. Most recipes have few total ratings, making many averages unreliable.</p>
<p>Across cuisines, cooking time varies distinctly: Cuban and Russian dishes are the longest, while Chinese and Filipino recipes are quicker to prepare. However, rating levels remain consistent regardless of cooking duration, indicating that user satisfaction isn’t tied to effort or time spent.</p>
<p>Overall, the dataset captures a rich cross-section of global cooking trends, where nutritional richness, preparation time, and popularity differ by cuisine, but ratings remain uniformly high and largely unaffected by these factors.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>