{
  "hash": "8e6f7cc7de7c0a7a54fe7e11d4a00046",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"TattooAttractivity\"\nformat: html\n---\n\n# **Tattoo Attractivity**\n\nThis data set investigates the perception of Srishti students without tattoos on whether tattoos enhance a person’s overall attractiveness.\n\n------------------------------------------------------------------------\n\n## Data Dictionary\n\nQualitative Variables\n\n:   -   **Name:** Factor indicating name of the participant.\n\n    -   **gender:** Factor indicating sex. Gender refers to either Male or Female.\n\n    -   **tattoo_attractive:** Factor indicating whether the participant finds tattoos attractive.\n\n## Our questions/ assumptions before performing EDA:\n\n-   Does gender influence whether someone finds tattoos attractive?\n-   Most people might find tattoos attractive, given the social and cultural factors at play in Srishti.\n\n------------------------------------------------------------------------\n\n#### Setting up the libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) # Our go-to package\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(infer) # An alternative package for inference using tidy data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(broom) # Clean test results in tibble form\nlibrary(skimr) # data inspection\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tinytable) # Pretty Tables\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'tinytable'\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(kableExtra) # Pretty Tables\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggprism) # Prism-like ggplot themes\nlibrary(resampledata3) # Datasets from Chihara and Hesterberg's book\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata3'\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(openintro) # datasets\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:mosaic':\n\n    dotPlot\n\nThe following objects are masked from 'package:lattice':\n\n    ethanol, lsegments\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(infer)\nlibrary(vcd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n\nAttaching package: 'vcd'\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(resampledata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata'\n\nThe following objects are masked from 'package:resampledata3':\n\n    Bushmeat, ChiMarathonMen, Cuckoos, FlightDelays, Groceries,\n    IceCream, MobileAds, NCBirths2004, Olympics2012, Phillies2009,\n    Recidivism\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(openintro)\nlibrary(readr)\nlibrary(naniar)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'naniar'\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(janitor)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(geofacet)\nlibrary(ggplot2)\n```\n:::\n\n\n#### Reading The Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo <- readr::read_delim(\"~/Downloads/Datasets for A3/tattooAttraction.csv\") %>% \n  janitor::clean_names(case = \"snake\") %>% \n  dplyr::glimpse()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 40 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Name, Gender, Tattoo_Attractive\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 3\n$ name              <chr> \"Aadya\", \"Abhinav\", \"Aditya\", \"Akash\", \"Amit\", \"Amog…\n$ gender            <chr> \"F\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"F\", \"M…\n$ tattoo_attractive <chr> \"Yes\", \"Yes\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\"…\n```\n\n\n:::\n\n```{.r .cell-code}\nTattoo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 3\n   name    gender tattoo_attractive\n   <chr>   <chr>  <chr>            \n 1 Aadya   F      Yes              \n 2 Abhinav M      Yes              \n 3 Aditya  M      No               \n 4 Akash   M      Yes              \n 5 Amit    M      No               \n 6 Amogh   M      Yes              \n 7 Anurag  M      Yes              \n 8 Arnav   M      Yes              \n 9 Aryan   M      Yes              \n10 Ashmita F      No               \n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\n#### Inspecting the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n visdat::vis_dat(Tattoo) + ggtitle(label= \"Tattoo Attractivity: Missing Data\", subtitle = \"Showing Variable Types\")\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  visdat::vis_miss(Tattoo)\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\nAll data present. Good job, team :D\n\n#### Munging the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 <- Tattoo %>% \n dplyr::select(tattoo_attractive, gender) %>%\n  tidyr::drop_na(., c(tattoo_attractive, gender)) %>%\n  # Re-level the factors\n  mutate(\n    tattoo_attractive = factor(tattoo_attractive,\n      levels = c(\"Yes\", \"No\"),\n      labels = c(\"Yes\", \"No\")\n    ),\n    gender = factor(gender,\n      levels = c(\"F\", \"M\"),\n      labels = c(\"F\", \"M\")\n    )\n  )\nglimpse(Tattoo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 2\n$ tattoo_attractive <fct> Yes, Yes, No, Yes, No, Yes, Yes, Yes, Yes, No, Yes, …\n$ gender            <fct> F, M, M, M, M, M, M, M, M, F, M, F, M, F, M, F, F, M…\n```\n\n\n:::\n:::\n\n\n#### Let's get a count of our data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 %>% \n  count(gender, tattoo_attractive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  gender tattoo_attractive     n\n  <fct>  <fct>             <int>\n1 F      Yes                  15\n2 F      No                    5\n3 M      Yes                  15\n4 M      No                    5\n```\n\n\n:::\n:::\n\n\nA perfect split of preferences? Wonder how statistically possible this is. For now let us make some graphs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 %>% \ngf_bar(~tattoo_attractive, fill = ~gender,\n       position = \"dodge\") %>% \ngf_labs(x=\"gender\",\n        y=\"count\",\n        title=\"Distribution of Tattoo Attractiveness Responses Across Genders\",\n         subtitle = \"Responses from students who do not have tattoos themselves\")\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFrom the chart, it appears that both male and female Srishti students show similar patterns in their responses. This suggests that gender does not play a major role in perceptions of tattoo attractiveness: both male and female students tend to view tattoos positively to a similar extent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattootable <- vcd::structable(gender ~ tattoo_attractive, data= Tattoo1)\nTattootable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  gender  F  M\ntattoo_attractive             \nYes                      15 15\nNo                        5  5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::mosaic(gender ~ tattoo_attractive, data = Tattoo1, \n            direction = \"v\", gp = shading_max, legend = FALSE)\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(gender ~ tattoo_attractive, data = Tattoo1, \n            type = \"expected\", direction = \"v\", gp = shading_max, \n            legend = FALSE)\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::assoc(gender ~ tattoo_attractive, \n           data = Tattoo1, \n           gp = shading_max, \n           legend = FALSE) \n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n:::\n\n\nAlthough this mosaic chart doesn't say much, it is pretty interesting to see how there is no deviation across the observed chart or the assoc chart. Let us look at some other graphs instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 %>%\n  gf_props(~tattoo_attractive,\n    fill = ~gender,\n    position = \"fill\"\n  ) %>%\n  gf_labs(\n    x = \"Do they find Tattoos Attractive?\",\n    title = \"Proportion of Tattoo Attractiveness Responses Across Genders\",\n        subtitle = \"Filled bar graph\"\n  )\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThis further validates our hypothesis above.\n\n------------------------------------------------------------------------\n\n### Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 %>%\n  summarize(prop = prop(tattoo_attractive, success = \"Yes\"), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   prop     n\n  <dbl> <int>\n1  0.75    40\n```\n\n\n:::\n:::\n\n\nOut of 40 responses, 75% of the sample set found Tattoos attractive. Let us quickly visualise that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTattoo1 %>%\n  gf_bar(~tattoo_attractive) %>%\n  gf_labs(\n    x = \"Do they find tattoos attractive?\",\n    title = \"Student Opinions on Tattoo Attractiveness\",\n    subtitle = \"Responses from students who do not have tattoos themselves\"\n  )\n```\n\n::: {.cell-output-display}\n![](TattooAttractivity_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### doing a binom test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~tattoo_attractive, data = Tattoo1, success = \"Yes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\ndata:  Tattoo1$tattoo_attractive  [with success = Yes]\nnumber of successes = 30, number of trials = 40, p-value = 0.002221\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5880380 0.8730852\nsample estimates:\nprobability of success \n                  0.75 \n```\n\n\n:::\n:::\n\n\nAwesome! let us turn it into a readable table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~tattoo_attractive, data = Tattoo1, success = \"Yes\") %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value parameter conf.low conf.high alternative\n     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      \n1     0.75        30 0.00222        40    0.588     0.873 two.sided  \n```\n\n\n:::\n:::\n\n\nAmong 40 Srishti students (without tattoos), 75% find tattoos attractive. The p.value is shown to be 0.002, which is lesser than 0.05; This is statistically significant! Confidence Intervals range from 58.8% and 87.3%, and does not include 50% in them. We can confidently conclude that a majority of students find tattoos attractive.\n\n------------------------------------------------------------------------\n\n#### Conclusion:\n\nThe data shows that gender doesn’t really make a difference in how Srishti students view tattoos: both male and female students seem to find them equally attractive.\n\nAbout 75% of students without tattoos said they find tattoos attractive, and the binomial test confirms this is statistically significant (p = 0.002). Since the confidence interval (58.8%–87.3%) doesn’t include 50%, we can confidently say that most students think tattoos make a person more attractive.\n\nOverall, the results suggest that tattoos are seen positively at Srishti, and the perception isn’t influenced much by gender.\n",
    "supporting": [
      "TattooAttractivity_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}