{
  "hash": "37c6385eb92718a007929bea411feade",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"weirddad\"\nformat: html\n---\n\n# **\"Is your Dad Weird?\"**\n\nThis data set explores a playful social observation among students from MIT and Srishti: examining whether they perceive their fathers as \"weird.\" Does being from a tech institute or a design institute influence one's perceptions of their parents?\n\n## Data Dictionary\n\nQualitative Variables\n\n:   -   **Name:** Factor indicating name of the participant.\n\n    -   **gender:** Factor indicating sex. Gender refers to Male, Female or Non-Binary.\n\n    -   **is_dad_weird:** Factor indicating whether the participant thinks their dad is weird or not.\n\n    -   **college:** Factor indicating the institute the participant is currently studying in.\n\n## Our assumptions before performing EDA:\n\n-   MIT folks might be less likely to think their dads are weird compared to Srishti folks.\n-   Females might be more likelier to think their dads are weird compared to males.\n\n------------------------------------------------------------------------\n\n#### Setting up the libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) # Our go-to package\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(infer) # An alternative package for inference using tidy data\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(broom) # Clean test results in tibble form\nlibrary(skimr) # data inspection\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tinytable) # Pretty Tables\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'tinytable'\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(kableExtra) # Pretty Tables\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggprism) # Prism-like ggplot themes\nlibrary(resampledata3) # Datasets from Chihara and Hesterberg's book\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata3'\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(openintro) # datasets\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:mosaic':\n\n    dotPlot\n\nThe following objects are masked from 'package:lattice':\n\n    ethanol, lsegments\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(infer)\nlibrary(vcd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n\nAttaching package: 'vcd'\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(resampledata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata'\n\nThe following objects are masked from 'package:resampledata3':\n\n    Bushmeat, ChiMarathonMen, Cuckoos, FlightDelays, Groceries,\n    IceCream, MobileAds, NCBirths2004, Olympics2012, Phillies2009,\n    Recidivism\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(openintro)\nlibrary(readr)\nlibrary(naniar)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'naniar'\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(janitor)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(geofacet)\nlibrary(ggplot2)\n```\n:::\n\n\n#### Reading the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWeirddad <- readr::read_delim(\"~/Downloads/Datasets for A3/weirddads.csv\") %>% \n  janitor::clean_names(case = \"snake\") %>% \n  dplyr::glimpse()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 65 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): gender, college, is_dad_weird, name\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 65\nColumns: 4\n$ gender       <chr> \"F\", \"F\", \"M\", \"F\", \"M\", \"M\", \"M\", \"M\", \"F\", \"M\", \"F\", \"M…\n$ college      <chr> \"SMI\", \"SMI\", \"SMI\", \"SMI\", \"MIT\", \"MIT\", \"MIT\", \"SMI\", \"…\n$ is_dad_weird <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"…\n$ name         <chr> \"Manya\", \"Sradha\", \"Arun\", \"Nidhi\", \"Shaurya\", \"Pratham\",…\n```\n\n\n:::\n\n```{.r .cell-code}\nWeirddad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 55 more rows\n```\n\n\n:::\n:::\n\n\n#### Inspecting the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n visdat::vis_dat(Weirddad) + ggtitle(label= \"Is your Dad Weird?: Missing Data\", subtitle = \"Showing Variable Types\")\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  visdat::vis_miss(Weirddad)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\nOnly 0.4% of data is missing, can do away with the data\n\n#### Munging the Data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweirddad_mod <- Weirddad %>% \n  mutate(across(where(is.character), as.factor)) %>% \n  tidyr::drop_na()\nweirddad_mod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 64 × 4\n   gender college is_dad_weird name   \n   <fct>  <fct>   <fct>        <fct>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 54 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweirddad_mod1 <- weirddad_mod %>% \n  dplyr::select(college, is_dad_weird, gender) %>%\n  tidyr::drop_na(., c(college, is_dad_weird)) %>%\n  # Re-level the factors\n  mutate(\n   college = factor(college,\n      levels = c(\"SMI\", \"MIT\"),\n      labels = c(\"SMI\", \"MIT\"),\n    ),\n    is_dad_weird = factor(is_dad_weird,\n      levels = c(\"Yes\", \"No\"),\n      labels = c(\"Yes\", \"No\")\n    ),\n   gender = factor(gender,\n      levels = c(\"F\", \"M\"),\n      labels = c(\"F\", \"M\"))\n  )\nglimpse(weirddad_mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 64\nColumns: 3\n$ college      <fct> SMI, SMI, SMI, SMI, MIT, MIT, MIT, SMI, SMI, SMI, SMI, SM…\n$ is_dad_weird <fct> No, No, No, Yes, No, No, No, No, Yes, Yes, Yes, Yes, No, …\n$ gender       <fct> F, F, M, F, M, M, M, M, F, M, F, M, F, F, M, M, F, M, M, …\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweirddad_mod %>%\n  drop_na() %>%\n  gf_bar(~is_dad_weird,\n    fill = ~gender,\n    position = \"dodge\"\n  ) %>%\n  gf_facet_grid(~college)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nSMI students are comparatively more split in their opinions: there’s a relatively balanced number of “Yes” and “No” responses. MIT students, on the other hand, overwhelmingly answered “No”: most don’t think their dad is weird. Across both colleges, the majority of students do not think their dad is weird. The trend is mainly driven by the college factor, not gender.\n\n#### What are the counts of Srishti v.s MIT students who think their dads are weird?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweirddad_mod1 %>% \n  dplyr::count(college, is_dad_weird)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  college is_dad_weird     n\n  <fct>   <fct>        <int>\n1 SMI     Yes             12\n2 SMI     No              19\n3 MIT     Yes              5\n4 MIT     No              28\n```\n\n\n:::\n:::\n\n\n-   SMI students: 12/31 = 38.7% said \"Yes\" (dad is weird)\n\n-   MIT students: 5/33 = 15.2% said \"Yes\" (dad is weird)\n\nSo far, we can conclude that SMI students are more than twice as likely to report having a weird dad compared to MIT students. Let's create a contingency table with just female and male (because we have insufficient data for NB).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- vcd::structable(gender ~ is_dad_weird, data= weirddad_mod1)\ncontingency_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             gender  F  M\nis_dad_weird             \nYes                  9  7\nNo                  23 24\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::mosaic(gender ~ is_dad_weird, data = weirddad_mod1, \n            direction = \"v\", gp = shading_max, legend = TRUE)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(gender ~ is_dad_weird, data = weirddad_mod1, \n            type = \"expected\", direction = \"v\", gp = shading_max, \n            legend = TRUE)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::assoc(gender ~ is_dad_weird, \n           data = weirddad_mod1, \n           gp = shading_max, \n           legend = TRUE) \n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(college ~ is_dad_weird, data = weirddad_mod1, \n            direction = \"v\", gp = shading_max, legend = TRUE)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(college ~ is_dad_weird, data = weirddad_mod1, \n            type = \"expected\", direction = \"v\", gp = shading_max, \n            legend = TRUE)\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::assoc(college ~ is_dad_weird, \n           data = weirddad_mod1, \n           gp = shading_max, \n           legend = TRUE) \n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n:::\n\n\nThe mosaic plots for gender vs is_dad_weird show a lack of strong association, indicated by the grey tiles. Through this, we could confirm that gender clearly does not play much of a role compared to college.\n\n------------------------------------------------------------------------\n\n#### Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table1 <- vcd::structable(college ~ is_dad_weird, data= weirddad_mod1)\ncontingency_table1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             college SMI MIT\nis_dad_weird                \nYes                   12   5\nNo                    19  28\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table2 <- as.table(contingency_table1)\ncontingency_table2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            college\nis_dad_weird SMI MIT\n         Yes  12   5\n         No   19  28\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object <- xchisq.test(contingency_table2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  x\nX-squared = 3.4202, df = 1, p-value = 0.0644\n\n   12        5   \n( 8.23)  ( 8.77) \n [1.30]   [1.22] \n< 1.31>  <-1.27> \n   \n   19       28   \n(22.77)  (24.23) \n [0.47]   [0.44] \n<-0.79>  < 0.76> \n   \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n:::\n\n\nReading the Pearson's Residuals:\n\n-   SMI/Yes: residual = 1.31 (more \"Yes\" than expected)\n\n-   SMI/No: residual = -0.79 (fewer \"No\" than expected)\n\n-   MIT/Yes: residual = -1.27 (fewer \"Yes\" than expected)\n\n-   MIT/No: residual = 0.76 (more \"No\" than expected)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object %>%\n  broom::tidy() %>%\n  select(statistic) %>%\n  as.numeric() -> X_squared_observed\nX_squared_observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.420189\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Determine the Chi-Square critical value\nX_squared_critical <- qchisq(\n  p = .05,\n  df = (2 - 1) * (2 - 1), \n  lower.tail = FALSE\n)\nX_squared_critical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.841459\n```\n\n\n:::\n:::\n\n\nHere, the observed chi-squared is 3.420189 and the chi-squared critical is 3.841459. Because the observed value is not higher than the critical value, we cannot prove that there is a statistically significant relationship between college and the weirdness of their dads.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::xqchisq(\n  p = 0.95, df = 1,\n  return = c(\"plot\"), verbose = F,\n  system = \"gg\"\n) %>%\n  gf_labs(\n    x = \"F value\", title = \"Critical and Observed Chi-Square Values\"\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_observed,\n    color = \"red\", linewidth = 1\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_critical,\n    color = \"dodgerblue\",\n    linewidth = 1\n  ) %>%\n  gf_annotate(\n    x = X_squared_observed -1.5, y = 0.35,\n    geom = \"label\", label = \"Observed\\n Chi-Square\",\n    fill = \"red\", alpha = 0.3\n  ) %>%\n  gf_annotate(\"curve\", X_squared_observed - 1.5,\n    y = 0.30, yend = 0.15,\n    xend = X_squared_observed - 0.2,\n    linewidth = 0.5, curvature = 0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_annotate(\n    x = X_squared_critical + 1.5, y = 0.35,\n    geom = \"label\", label = \"Critical\\n Chi-Square\",\n    fill = \"lightblue\"\n  ) %>%\n  gf_annotate(\"curve\", X_squared_critical + 1.5,\n    y = 0.30, yend = 0.15,\n    xend = X_squared_critical + 0.2,\n    linewidth = 0.5, curvature = -0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_refine(\n    scale_y_continuous(expand = expansion(add = c(0, 0.01))),\n    scale_x_continuous(expand = expansion(add = c(0, 1)))\n  )\n```\n\n::: {.cell-output-display}\n![](weirddad_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe gap between the red and blue lines shows that the data was close to being statistically significant but fell short by 0.42 points. Although our EDA shows a clear trend, this could be due to chance. More data is needed.\n\n------------------------------------------------------------------------\n\n### Conclusion\n\nSMI students are more likely to describe their dads as weird than MIT students, but the difference is not statistically significant (chi-squared-test = 3.42 \\< 3.84). Gender also shows no clear association, as indicated by the grey mosaic plot. Overall, college seems to influence responses more than gender, though more data is needed to confirm this trend.\n",
    "supporting": [
      "weirddad_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}